# Generated by Django 5.2.6 on 2025-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reviewed', 'Reviewed Content'), ('banned_user', 'Banned User'), ('unbanned_user', 'Unbanned User'), ('updated_status', 'Updated Content Status'), ('feedback_given', 'Feedback Given')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
