# Generated by Django 5.2.6 on 2025-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('flagged', 'Flagged'), ('banned', 'Banned')], default='safe', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('toxic', 'Toxic'), ('spam', 'Spam'), ('fraud', 'Fraud'), ('drug', 'Drug-related'), ('harassment', 'Harassment'), ('safe', 'Safe')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('review', 'Review'), ('ban', 'Ban')], default='review', max_length=20)),
            ],
        ),
    ]
